<?php

/**
 * @file
 * Contains tweet_feed.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function tweet_feed_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the tweet_feed module.
    case 'help.page.tweet_feed':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('A custom Twitter implementation of both twitter feeds and user profiles.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function tweet_feed_theme() {
  return [
    'tweet_feed' => [
      'render element' => 'children',
    ],
  ];
}
